apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/codimite-assesment/app:latest
        ports:
        - containerPort: 8080
