name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate with GCP
      - name: Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-service:latest .

      # Push the Docker image to GCR
      - name: Push Docker Image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-service:latest

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Authenticate kubectl using gcloud
      - name: Authenticate kubectl
        run: |
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} \
          --region ${{ secrets.GCP_CLUSTER_REGION }} \
          --project ${{ secrets.GCP_PROJECT_ID }}

      # Deploy to GKE
      - name: Update Deployment in GKE
        run: |
          kubectl set image deployment/my-deployment my-container=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-service:latest --record
          kubectl rollout status deployment/my-deployment
